name: Build & Publish Docker Image

on:
  push:
    branches_ignore: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Plex VM
    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish Docker Image
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(date +%s)
        docker build --tag bossanova456/plex-bot:${TAG} .
        docker login -u bossanova456 -p $DOCKER_TOKEN 
        docker push bossanova456/plex-bot:${TAG}
