name: Docker Image CI

on:
  push:
    workflow_dispatch: [ "main" ]

jobs:
  build:
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag plex-bot:$(date +%s)